global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'prommaster'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

scrape_configs:
  - job_name: federate
    basic_auth:
      #username: <username>#
      #password: <password>#
    scrape_interval: 10s
    honor_labels: true
    metrics_path: '/federate'
    params:
      match[]:
      - '{job="cadvisor"}'
      - '{job="node-exporter"}'
      - '{job="dockerd-exporter"}'
    static_configs:
      - targets:
        - #prom_ip:<port>#
    

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100


alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
